// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WIS.Infrastructure;
using WIS.Infrastructure.Persistence;

#nullable disable

namespace WIS.Infrastructure.Migrations
{
    [DbContext(typeof(WareHouseDbContext))]
    [Migration("20251023153805_InitialMigrationAddInventoryItemAndInventoryStockTables")]
    partial class InitialMigrationAddInventoryItemAndInventoryStockTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WIS.Infrastructure.Inventory.Entities.InventoryItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ProductType")
                        .HasColumnType("integer");

                    b.Property<int>("Size")
                        .HasMaxLength(10)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("WIS.Infrastructure.Inventory.Entities.InventoryStockModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("InventoryItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId")
                        .IsUnique();

                    b.ToTable("InventoryStocks");
                });

            modelBuilder.Entity("WIS.Infrastructure.Inventory.Entities.InventoryStockModel", b =>
                {
                    b.HasOne("WIS.Infrastructure.Inventory.Entities.InventoryItemModel", "InventoryItemModel")
                        .WithOne("InventoryStock")
                        .HasForeignKey("WIS.Infrastructure.Inventory.Entities.InventoryStockModel", "InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("InventoryItemModel");
                });

            modelBuilder.Entity("WIS.Infrastructure.Inventory.Entities.InventoryItemModel", b =>
                {
                    b.Navigation("InventoryStock");
                });
#pragma warning restore 612, 618
        }
    }
}
